const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'room-owner-test-'));
 const server=spawn('/Library/Frameworks/Python.framework/Versions/3.14/bin/python3',['backend/server.py','--port','8933','--data-dir',dir],{env:{...process.env,ROOM_OWNER_PASSWORD:'initial-browser-test-password'},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('server exited '+code)));});
 let browser;
 try{
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-webgl']});
 const context=await browser.newContext({viewport:{width:1150,height:850},reducedMotion:'reduce'}),admin=await context.newPage();const errors=[];admin.on('pageerror',e=>errors.push(String(e)));
 await admin.goto('http://127.0.0.1:8933/admin/');await admin.locator('#password').fill('initial-browser-test-password');await admin.locator('#login-form button').click();await admin.locator('#new-password').fill('new-browser-test-password');await admin.locator('#change-form button').click();await admin.locator('#password').fill('new-browser-test-password');await admin.locator('#login-form button').click();await admin.locator('#studio').waitFor({state:'visible'});
 await admin.locator('[data-collection="notebook"]').click();await admin.locator('#add-item').click();await admin.locator('[name=title]').fill('Browser test note');await admin.locator('[name=body]').fill('Only a temporary test fixture.');await admin.locator('[name=stickers]').fill('测试, 星星');await admin.locator('[name=published]').check();await admin.locator('#save-item').click();await admin.locator('#editor').waitFor({state:'hidden'});
 assert.match(await admin.locator('#items').innerText(),/Browser test note/);
 await admin.locator('#add-item').click();await admin.locator('[name=title]').fill('Private fixture');await admin.locator('#save-item').click();await admin.locator('#editor').waitFor({state:'hidden'});
 await admin.locator('[data-up]').nth(1).click();await admin.waitForTimeout(300);assert.match(await admin.locator('.content-item').first().innerText(),/Private fixture/);
 await admin.locator('[data-collection="photoWall"]').click();await admin.locator('#add-item').click();await admin.locator('[name=title]').fill('Uploaded fixture');
 await admin.locator('#upload').setInputFiles({name:'not-image.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await admin.waitForFunction(()=>document.getElementById('media-status').textContent.includes('支持'));
 await admin.locator('#upload').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});await admin.waitForFunction(()=>document.getElementById('media-status').textContent.includes('已上传'));await admin.locator('[name=published]').check();await admin.locator('#save-item').click();await admin.locator('#editor').waitFor({state:'hidden'});await admin.screenshot({path:'/tmp/tahoe-admin.png'});
 await admin.locator('[data-collection="map"]').click();await admin.locator('#add-item').click();await admin.locator('[name=title]').fill('Queenstown memory');await admin.locator('[name=city]').fill('Queenstown');await admin.locator('[name=country]').fill('New Zealand');await admin.locator('[name=body]').fill('A quiet afternoon by the lake.');const mapEditor=admin.locator('#map-position-editor');const mapBox=await mapEditor.boundingBox();await mapEditor.click({position:{x:mapBox.width*.78,y:mapBox.height*.72}});assert(Number(await admin.locator('[name=x]').inputValue())>.7);await admin.locator('[name=published]').check();await admin.locator('#save-item').click();await admin.locator('#editor').waitFor({state:'hidden'});assert.match(await admin.locator('#items').innerText(),/Queenstown/);
 await admin.locator('#add-item').click();await admin.locator('[name=role]').selectOption('map-image');await admin.locator('[name=title]').fill('My world map');await admin.locator('#upload').setInputFiles({name:'map.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});await admin.waitForFunction(()=>document.getElementById('media-status').textContent.includes('已上传'));await admin.locator('[name=published]').check();await admin.locator('#save-item').click();await admin.locator('#editor').waitFor({state:'hidden'});
 const visitor=await browser.newContext({reducedMotion:'reduce'}),publicPage=await visitor.newPage();await publicPage.goto('http://127.0.0.1:8933/');await publicPage.waitForFunction(()=>window.__ROOM_INTERACTIONS__,{},{timeout:60000});assert.equal(await publicPage.evaluate(()=>window.__ROOM_INTERACTIONS__.content.notebookPages.length),1);assert.equal(await publicPage.evaluate(()=>window.__ROOM_INTERACTIONS__.content.photos.length),1);await publicPage.waitForFunction(()=>window.__ROOM_APP__.photoMeshes[0].material.map!==null);
 assert.equal(await publicPage.evaluate(()=>window.__ROOM_INTERACTIONS__.content.travelPins[0].city),'Queenstown');assert.match(await publicPage.evaluate(()=>window.__ROOM_INTERACTIONS__.content.map.image),/api\/media\//);
 await admin.locator('[data-collection="notebook"]').click();await admin.locator('[data-edit]').nth(1).click();await admin.locator('[name=title]').fill('Updated without deployment');await admin.locator('#save-item').click();await admin.locator('#editor').waitFor({state:'hidden'});await publicPage.evaluate(()=>window.__ROOM_INTERACTIONS__.refreshContent());await publicPage.waitForFunction(()=>window.__ROOM_INTERACTIONS__.content.notebookPages[0].title==='Updated without deployment');await publicPage.locator('[data-object=notebook]').click();await publicPage.waitForFunction(()=>window.__ROOM_INTERACTIONS__.controller.phase==='experience');assert.equal(await publicPage.locator('.journal-page h2').first().textContent(),'Updated without deployment');await publicPage.locator('#return-room').click();await publicPage.waitForFunction(()=>window.__ROOM_INTERACTIONS__.controller.phase==='overview');
 await admin.locator('[data-edit]').nth(1).click();await admin.route('**/api/items/*',route=>route.abort());await admin.locator('#save-item').click();await admin.waitForFunction(()=>document.getElementById('form-status').textContent.includes('网络'));assert.equal(await admin.locator('#editor').isVisible(),true);await admin.unroute('**/api/items/*');await admin.locator('#cancel').click();
 await admin.setViewportSize({width:390,height:844});await admin.screenshot({path:'/tmp/tahoe-admin-mobile.png'});assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await admin.locator('#logout').click();await admin.locator('#login-panel').waitFor({state:'visible'});assert.equal((await publicPage.request.get('http://127.0.0.1:8933/api/collections')).status(),401);
 assert.deepEqual(errors,[]);console.log('PASS browser login/password change, create/edit/upload/reorder, private filtering, public live refresh, mobile admin, upload/save error feedback, logout');
 } finally{if(browser)await browser.close();server.kill('SIGTERM');fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1);});
