(()=>{
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let csrf='',collections=[],selected='monitor',editing=null,mediaId=null,upload=null;
 async function api(path,method='GET',body){const response=await fetch('../api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body!==undefined?{body:JSON.stringify(body)}:{})});let result;try{result=await response.json();}catch{throw Error('内容服务未启动，请使用 backend/server.py 启动网站。');}if(!response.ok){if(response.status===401&&path!=='login')showLogin();throw Error(result.error||'请求失败');}return result;}
 function status(message){$('status').textContent=message;}
 function showLogin(){csrf='';$('studio').hidden=true;$('change-panel').hidden=true;$('logout').hidden=true;$('login-panel').hidden=false;if($('editor').open)$('editor').close();}
 async function entered(session){csrf=session.csrf;$('login-panel').hidden=true;$('logout').hidden=false;$('password').value='';if(session.mustChangePassword){$('change-panel').hidden=false;$('studio').hidden=true;status('首次登录，请设置自己的密码。');return;}$('change-panel').hidden=true;$('studio').hidden=false;await refresh();}
 async function refresh(){const data=await api('collections');collections=data.collections;render();status('已连接 · 内容保存在服务器，公开内容会自动同步到房间。');}
 function current(){return collections.find(c=>c.id===selected);}
 function render(){
  $('objects').innerHTML=collections.map(c=>`<button data-collection="${c.id}" aria-current="${c.id===selected}">${esc(c.title)} <small>${c.items.length}</small></button>`).join('');
  $('objects').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.collection;render();});
  $('collection-title').textContent=current()?.title||'';
  $('items').innerHTML=current()?.items.map((i,n)=>`<article class="content-item"><div><h3>${esc(i.title)} <span class="badge ${i.published?'':'private'}">${i.published?'公开':'私有'}</span></h3><p>${esc(i.description||i.body.slice(0,100))}</p><small>${esc(i.kind)}${i.media_id?' · 已关联文件':''}</small></div><div class="item-actions"><button data-edit="${i.id}">编辑</button><button data-up="${i.id}" aria-label="上移 ${esc(i.title)}" ${n===0?'disabled':''}>↑</button><button data-down="${i.id}" aria-label="下移 ${esc(i.title)}" ${n===current().items.length-1?'disabled':''}>↓</button><button data-delete="${i.id}">删除</button></div></article>`).join('')||'<p class="muted">暂无内容。点击“添加内容”，为这个物件创建第一条记录。</p>';
  $('items').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(current().items.find(i=>i.id===b.dataset.edit)));
  $('items').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('删除这条内容？关联文件保留为私有，不会影响其他引用。'))return;try{await api('items/'+b.dataset.delete,'DELETE');await refresh();}catch(e){status(e.message);}});
  ['up','down'].forEach(action=>$('items').querySelectorAll('[data-'+action+']').forEach(b=>b.onclick=async()=>{const ids=current().items.map(i=>i.id),index=ids.indexOf(b.dataset[action]),next=index+(action==='up'?-1:1);[ids[index],ids[next]]=[ids[next],ids[index]];try{await api('reorder','POST',{collection_id:selected,ids});await refresh();}catch(e){status(e.message);}}));
 }
 function edit(item){editing=item||null;mediaId=item?.media_id||null;const f=$('item-form');f.reset();['title','description','body','url','kind'].forEach(k=>{if(item)f.elements[k].value=item[k];});if(!item)f.elements.kind.value={monitor:'pdf',notebook:'text',turntable:'audio',map:'text',photoWall:'image',books:'text'}[selected];f.elements.published.checked=item?.published||false;f.elements.creator.value=item?.metadata?.artist||item?.metadata?.author||'';['date','city','country','x','y'].forEach(k=>f.elements[k].value=item?.metadata?.[k]??'');$('map-fields').hidden=selected!=='map';$('media-status').textContent=mediaId?'已关联服务器文件':'';$('remove-media').hidden=!mediaId;$('form-status').textContent='';$('upload-progress').hidden=true;$('save-item').disabled=false;$('editor-title').textContent=item?'编辑内容':'添加内容';$('editor').showModal();f.elements.title.focus();}
 $('add-item').onclick=()=>edit();$('cancel').onclick=()=>{if(upload)upload.abort();$('editor').close();};$('editor').addEventListener('cancel',()=>{if(upload)upload.abort();});
 $('remove-media').onclick=()=>{mediaId=null;$('remove-media').hidden=true;$('media-status').textContent='保存后解除关联；文件不会被公开。';};
 $('upload').onchange=()=>{
  const file=$('upload').files[0];if(!file)return;if(file.size>64*1024*1024){$('media-status').textContent='文件超过 64 MB，请压缩或使用关联链接。';return;}
  if(upload)upload.abort();const xhr=new XMLHttpRequest();upload=xhr;xhr.open('POST','../api/media');xhr.withCredentials=true;xhr.setRequestHeader('X-CSRF-Token',csrf);xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');$('save-item').disabled=true;$('upload-progress').hidden=false;$('upload-progress').value=0;$('media-status').textContent='正在上传 '+file.name;
  xhr.upload.onprogress=e=>{if(e.lengthComputable)$('upload-progress').value=e.loaded/e.total*100;};
  xhr.onload=()=>{try{const result=JSON.parse(xhr.responseText);if(xhr.status<200||xhr.status>=300)throw Error(result.error);mediaId=result.id;$('media-status').textContent='已上传：'+file.name+'（保存前仅 Owner 可读）';$('remove-media').hidden=false;const mime=result.mime;$('item-form').elements.kind.value=mime.startsWith('image/')?'image':mime.startsWith('audio/')?'audio':mime.startsWith('video/')?'video':'pdf';}catch(e){$('media-status').textContent=e.message||'上传失败，请重试';}};
  xhr.onerror=()=>{$('media-status').textContent='网络错误，上传失败，请重试。';};xhr.onabort=()=>{$('media-status').textContent='上传已取消。';};xhr.onloadend=()=>{$('save-item').disabled=false;upload=null;};xhr.send(file);
 };
 $('item-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,metadata={...(editing?.metadata||{}),date:f.elements.date.value,author:f.elements.creator.value,artist:f.elements.creator.value};if(selected==='map')Object.assign(metadata,{city:f.elements.city.value,country:f.elements.country.value,x:f.elements.x.value===''?null:Number(f.elements.x.value),y:f.elements.y.value===''?null:Number(f.elements.y.value)});const item={collection_id:selected,kind:f.elements.kind.value,title:f.elements.title.value,description:f.elements.description.value,body:f.elements.body.value,url:f.elements.url.value,media_id:mediaId,published:f.elements.published.checked,position:editing?.position??current().items.length,metadata};$('save-item').disabled=true;$('form-status').textContent='正在保存…';try{await api(editing?'items/'+editing.id:'items',editing?'PUT':'POST',item);$('editor').close();await refresh();}catch(error){$('form-status').textContent=error.message;}finally{$('save-item').disabled=false;}};
 $('login-form').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{await entered(await api('login','POST',{password:$('password').value}));}catch(error){status(error.message);}finally{button.disabled=false;}};
 $('change-form').onsubmit=async e=>{e.preventDefault();try{await api('password','POST',{password:$('new-password').value});$('new-password').value='';showLogin();status('密码已更新，请使用新密码登录。');}catch(error){status(error.message);}};
 $('logout').onclick=async()=>{try{await api('logout','POST');showLogin();status('已退出登录。');}catch(error){status(error.message);}};
 (async()=>{try{await api('health');try{await entered(await api('session'));}catch{showLogin();status('请使用 Owner 密码登录。');}}catch(e){status('内容服务未接通：请运行 backend/server.py。此页面不会模拟登录或上传。');}})();
})();
