(()=>{
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),schema=RoomContentSchema.objects;
 let csrf='',collections=[],selected='monitor',editing=null,mediaId=null,upload=null;
 async function api(path,method='GET',body){let response;try{response=await fetch('../api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body!==undefined?{body:JSON.stringify(body)}:{})});}catch{throw Error('网络请求失败，请检查连接后重试。');}let result;try{result=await response.json();}catch{throw Error('内容服务未启动，请使用 backend/server.py 启动网站。');}if(!response.ok){if(response.status===401&&path!=='login')showLogin();throw Error(result.error||'请求失败');}return result;}
 function status(message){$('status').textContent=message;}
 function showLogin(){csrf='';$('studio').hidden=true;$('change-panel').hidden=true;$('logout').hidden=true;$('login-panel').hidden=false;if($('editor').open)$('editor').close();}
 async function entered(session){csrf=session.csrf;$('login-panel').hidden=true;$('logout').hidden=false;$('password').value='';if(session.mustChangePassword){$('change-panel').hidden=false;$('studio').hidden=true;status('首次登录，请设置自己的密码。');return;}$('change-panel').hidden=true;$('studio').hidden=false;await refresh();}
 async function refresh(){const data=await api('collections');collections=data.collections;render();status('已连接 · 内容保存在服务器，公开内容会自动同步到房间。');}
 function current(){return collections.find(c=>c.id===selected);}
 function summary(item){const meta=item.metadata||{};if(selected==='map')return meta.role==='map-image'?'房间墙面的自定义世界地图':[meta.city,meta.country,item.description].filter(Boolean).join(' · ');if(selected==='books')return [meta.author,item.body||item.description].filter(Boolean).join(' · ');if(selected==='turntable')return [meta.artist,meta.moodTags,item.body||item.description].filter(Boolean).join(' · ');return item.description||item.body.slice(0,110);}
 function render(){
  $('objects').innerHTML=collections.map(c=>`<button data-collection="${c.id}" aria-current="${c.id===selected}">${esc(schema[c.id]?.label||c.title)} <small>${c.items.length}</small></button>`).join('');
  $('objects').querySelectorAll('button').forEach(button=>button.onclick=()=>{selected=button.dataset.collection;render();});
  const definition=schema[selected];$('collection-title').textContent=definition?.entry||current()?.title||'';$('collection-description').textContent=definition?.description||'';
  $('items').innerHTML=current()?.items.map((item,index)=>`<article class="content-item"><div><h3>${esc(item.title)} <span class="badge ${item.published?'':'private'}">${item.published?'公开':'私有'}</span></h3><p>${esc(summary(item))}</p><small>${esc(item.metadata?.role==='map-image'?'地图图片':definition?.entry||item.kind)}${item.media_id?' · 已关联文件':''}</small></div><div class="item-actions"><button data-edit="${item.id}">编辑</button><button data-up="${item.id}" aria-label="上移 ${esc(item.title)}" ${index===0?'disabled':''}>↑</button><button data-down="${item.id}" aria-label="下移 ${esc(item.title)}" ${index===current().items.length-1?'disabled':''}>↓</button><button data-delete="${item.id}">删除</button></div></article>`).join('')||'<p class="muted">暂无内容。点击“添加内容”，为这个物件创建第一条记录。</p>';
  $('items').querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>edit(current().items.find(item=>item.id===button.dataset.edit)));
  $('items').querySelectorAll('[data-delete]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条内容？关联文件会保留为私有。'))return;try{await api('items/'+button.dataset.delete,'DELETE');await refresh();}catch(error){status(error.message);}});
  ['up','down'].forEach(action=>$('items').querySelectorAll('[data-'+action+']').forEach(button=>button.onclick=async()=>{const ids=current().items.map(item=>item.id),index=ids.indexOf(button.dataset[action]),next=index+(action==='up'?-1:1);[ids[index],ids[next]]=[ids[next],ids[index]];try{await api('reorder','POST',{collection_id:selected,ids});await refresh();}catch(error){status(error.message);}}));
 }
 function setValue(form,name,value){if(form.elements[name])form.elements[name].value=value??'';}
 function setFieldVisibility(){
  document.querySelectorAll('[data-for]').forEach(element=>element.hidden=!element.dataset.for.split(',').includes(selected));
  const form=$('item-form'),role=form.elements.role.value,isMapImage=selected==='map'&&role==='map-image';$('map-pin-fields').hidden=selected!=='map'||isMapImage;
  $('description-label').firstChild.textContent=selected==='map'?'明信片短句 ':selected==='photoWall'?'照片说明 ':selected==='books'?'一句短评 ':selected==='turntable'?'歌曲 / 歌单说明 ':'摘要 ';
  $('body-label').firstChild.textContent=selected==='notebook'?'手账正文 ':selected==='map'?'旅行长故事 ':selected==='turntable'?'关于它的记忆 ':selected==='books'?'个人短评 / 阅读记忆 ':selected==='photoWall'?'照片背后的故事 ':'正文 ';
  $('url-label').firstChild.textContent=selected==='turntable'?'网易云音乐链接 ':selected==='books'?'豆瓣链接 ':'关联链接 ';
  $('upload-label').firstChild.textContent=isMapImage?'上传自定义世界地图图片 ':selected==='books'?'上传书封（可选） ':selected==='photoWall'?'上传照片 ':selected==='notebook'?'附一张页面图片（可选） ':selected==='turntable'?'上传有权使用的音频（可选） ':'上传媒体（可选） ';
  if(isMapImage)form.elements.kind.value='image';
 }
 function mapImageUrl(){const item=current()?.items.find(entry=>entry.metadata?.role==='map-image'&&entry.media_url);return item?'../'+item.media_url:'';}
 function syncDot(){const form=$('item-form'),x=Math.max(0,Math.min(1,Number(form.elements.x.value)||0)),y=Math.max(0,Math.min(1,Number(form.elements.y.value)||0)),dot=$('map-position-dot');dot.style.left=x*100+'%';dot.style.top=y*100+'%';}
 function edit(item){
  editing=item||null;mediaId=item?.media_id||null;const form=$('item-form'),defaults=RoomContentSchema.defaults(selected),metadata=item?.metadata||defaults.metadata;form.reset();
  ['title','description','body','url'].forEach(key=>setValue(form,key,item?.[key]));setValue(form,'kind',item?.kind||defaults.kind);setValue(form,'role',metadata.role||'pin');['author','artist','date','location','tags','rating','moodTags','coverUrl','stickers','city','country','x','y'].forEach(key=>setValue(form,key,metadata[key]));setValue(form,'photoUrls',Array.isArray(metadata.photoUrls)?metadata.photoUrls.join('\n'):'');
  form.elements.published.checked=item?.published||false;$('media-status').textContent=mediaId?'已关联服务器文件':'';$('remove-media').hidden=!mediaId;$('form-status').textContent='';$('upload-progress').hidden=true;$('save-item').disabled=false;$('editor-title').textContent=item?'编辑'+schema[selected].entry:'添加'+schema[selected].entry;$('editor-object').textContent=schema[selected].label.toUpperCase();$('object-guidance').textContent=schema[selected].description;
  const mapUrl=mapImageUrl();$('map-position-editor').style.backgroundImage=mapUrl?`linear-gradient(#ffffff20,#ffffff20),url("${mapUrl}")`:'';setFieldVisibility();syncDot();$('editor').showModal();form.elements.title.focus();
 }
 $('add-item').onclick=()=>edit();$('cancel').onclick=()=>{if(upload)upload.abort();$('editor').close();};$('editor').addEventListener('cancel',()=>{if(upload)upload.abort();});$('item-form').elements.role.onchange=setFieldVisibility;
 ['x','y'].forEach(name=>$('item-form').elements[name].addEventListener('input',syncDot));
 function movePin(event){const rect=$('map-position-editor').getBoundingClientRect(),form=$('item-form');form.elements.x.value=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)).toFixed(4);form.elements.y.value=Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height)).toFixed(4);syncDot();}
 $('map-position-editor').addEventListener('pointerdown',event=>{event.currentTarget.setPointerCapture(event.pointerId);movePin(event);});$('map-position-editor').addEventListener('pointermove',event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))movePin(event);});$('map-position-editor').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const form=$('item-form'),dx=event.key==='ArrowLeft'?-0.01:(event.key==='ArrowRight'?0.01:0),dy=event.key==='ArrowUp'?-0.01:(event.key==='ArrowDown'?0.01:0);form.elements.x.value=Math.max(0,Math.min(1,Number(form.elements.x.value)+dx)).toFixed(4);form.elements.y.value=Math.max(0,Math.min(1,Number(form.elements.y.value)+dy)).toFixed(4);syncDot();});
 $('remove-media').onclick=()=>{mediaId=null;$('remove-media').hidden=true;$('media-status').textContent='保存后解除关联；文件不会被公开。';};
 $('upload').onchange=()=>{
  const file=$('upload').files[0];if(!file)return;if(file.size>64*1024*1024){$('media-status').textContent='文件超过 64 MB，请压缩或使用关联链接。';return;}
  if(upload)upload.abort();const xhr=new XMLHttpRequest();upload=xhr;xhr.open('POST','../api/media');xhr.withCredentials=true;xhr.setRequestHeader('X-CSRF-Token',csrf);xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');$('save-item').disabled=true;$('upload-progress').hidden=false;$('upload-progress').value=0;$('media-status').textContent='正在上传 '+file.name;
  xhr.upload.onprogress=event=>{if(event.lengthComputable)$('upload-progress').value=event.loaded/event.total*100;};xhr.onload=()=>{try{const result=JSON.parse(xhr.responseText);if(xhr.status<200||xhr.status>=300)throw Error(result.error);mediaId=result.id;$('media-status').textContent='已上传：'+file.name+'（保存前仅 Owner 可读）';$('remove-media').hidden=false;const mime=result.mime;$('item-form').elements.kind.value=mime.startsWith('image/')?'image':mime.startsWith('audio/')?'audio':mime.startsWith('video/')?'video':'pdf';if(selected==='map'&&$('item-form').elements.role.value==='map-image')$('map-position-editor').style.backgroundImage=`url("../api/media/${mediaId}")`;}catch(error){$('media-status').textContent=error.message||'上传失败，请重试';}};xhr.onerror=()=>{$('media-status').textContent='网络错误，上传失败，请重试。';};xhr.onabort=()=>{$('media-status').textContent='上传已取消。';};xhr.onloadend=()=>{$('save-item').disabled=false;upload=null;};xhr.send(file);
 };
 $('item-form').onsubmit=async event=>{
  event.preventDefault();const form=event.currentTarget,metadata={};RoomContentSchema.metadata[selected].forEach(key=>{let value=form.elements[key]?.value??'';if(key==='rating'&&value!=='')value=Number(value);if(key==='x'||key==='y')value=value===''?null:Number(value);if(key==='photoUrls')value=value.split('\n').map(v=>v.trim()).filter(Boolean);metadata[key]=value;});
  if(selected==='map'&&metadata.role==='map-image'){delete metadata.x;delete metadata.y;delete metadata.city;delete metadata.country;delete metadata.photoUrls;}
  let kind=form.elements.kind.value;if(selected==='turntable'&&!mediaId)kind=form.elements.url.value?'link':'text';if(selected==='books'&&!mediaId)kind='text';if(selected==='notebook'&&!mediaId)kind='text';if(selected==='map'&&metadata.role!=='map-image'&&!mediaId)kind='text';
  const item={collection_id:selected,kind,title:form.elements.title.value,description:form.elements.description.value,body:form.elements.body.value,url:form.elements.url?.value||'',media_id:mediaId,published:form.elements.published.checked,position:editing?.position??current().items.length,metadata};$('save-item').disabled=true;$('form-status').textContent='正在保存…';try{await api(editing?'items/'+editing.id:'items',editing?'PUT':'POST',item);$('editor').close();await refresh();}catch(error){$('form-status').textContent=error.message;}finally{$('save-item').disabled=false;}
 };
 $('login-form').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await entered(await api('login','POST',{password:$('password').value}));}catch(error){status(error.message);}finally{button.disabled=false;}};
 $('change-form').onsubmit=async event=>{event.preventDefault();try{await api('password','POST',{password:$('new-password').value});$('new-password').value='';showLogin();status('密码已更新，请使用新密码登录。');}catch(error){status(error.message);}};
 $('logout').onclick=async()=>{try{await api('logout','POST');showLogin();status('已退出登录。');}catch(error){status(error.message);}};
 (async()=>{try{await api('health');try{await entered(await api('session'));}catch{showLogin();status('请使用 Owner 密码登录。');}}catch{status('内容服务未接通：请运行 backend/server.py。此页面不会模拟登录或上传。');}})();
})();
