/* Local-first build mode: catalog → validated placement → versioned world objects → undo/redo. */
window.WorldBuildMode=(()=>{
 const STORAGE='personal-world-build:v1',SAVE_VERSION=1;
 const deep=value=>JSON.parse(JSON.stringify(value));
 const uid=()=>globalThis.crypto?.randomUUID?.()||'object-'+Date.now()+'-'+Math.random().toString(16).slice(2);
 function fresh(){return {schema:'personal-world-build',saveVersion:SAVE_VERSION,revision:0,objects:[]};}
 function read(){try{const value=JSON.parse(localStorage.getItem(STORAGE)||'null');if(value?.schema==='personal-world-build'&&value.saveVersion===1&&Array.isArray(value.objects))return value;}catch(error){console.warn('Build save ignored',error);}return fresh();}
 function write(state){localStorage.setItem(STORAGE,JSON.stringify(state));}
 function initUI(catalog){
  const toggle=document.createElement('button');toggle.id='build-toggle';toggle.textContent='🌱 建造';toggle.setAttribute('aria-expanded','false');
  const panel=document.createElement('aside');panel.id='build-panel';panel.hidden=true;panel.innerHTML='<header><strong>湖畔建造</strong><button data-command="close" aria-label="关闭建造模式">×</button></header><p class="build-help">选择资产后点击地面放置。绿色可建造，红色表示违反湖岸、道路、坡度或间距规则。</p><div class="build-assets"></div><div class="build-actions"><button data-command="select">选择</button><button data-command="move">移动</button><button data-command="rotate">旋转</button><button data-command="delete">删除</button><button data-command="undo">撤销</button><button data-command="redo">重做</button></div><p class="build-status" role="status">尚未进入建造模式</p>';
  const assets=panel.querySelector('.build-assets');for(const asset of catalog.all){const b=document.createElement('button');b.dataset.asset=asset.id;b.innerHTML='<span>'+({flower:'🌼',tree:'🌲',house:'🏠'}[asset.category]||'◇')+'</span>'+asset.displayName+'<small>'+asset.economy.cost+' 资源</small>';assets.appendChild(b);}
  document.body.append(toggle,panel);return {toggle,panel,status:panel.querySelector('.build-status')};
 }
 async function init(app){
  const T=THREE,catalog=await WorldAssetLibrary.load(),surface=app.environment.surface,ui=initUI(catalog),root=new T.Group();root.name='player-built-world';app.scene.add(root);
  const raycaster=new T.Raycaster(),pointer=new T.Vector2(),terrain=app.scene.getObjectByName('sampled-terrain'),past=[],future=[];let state=read(),active=false,tool='select',assetId=null,selectedId=null,ghost=null,preview=null,selection=null,rotation=0;
  const meshes=new Map();
  function materialGhost(object,valid){object.traverse(o=>{if(!o.isMesh)return;if(!o.userData.buildGhostMaterials){o.material=(Array.isArray(o.material)?o.material:[o.material]).map(m=>{const n=m.clone();n.transparent=true;n.opacity=.48;n.depthWrite=false;n.userData.buildGhost=true;return n;});o.userData.buildGhostMaterials=true;}for(const m of (Array.isArray(o.material)?o.material:[o.material]))m.color.set(valid?'#67d98a':'#e76868');});}
  function disposeObject(object){object.traverse(o=>{if(o.geometry)o.geometry.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]).filter(Boolean))m.dispose();});if(object.parent)object.parent.remove(object);}
  function objectFor(record){const object=catalog.create(record.assetId),asset=catalog.get(record.assetId);object.position.fromArray(record.position);object.rotation.y=record.rotationY||0;object.scale.setScalar(record.scale||1);object.userData.worldObjectId=record.id;object.userData.assetId=record.assetId;object.traverse(o=>{o.userData.worldObjectId=record.id;});if(asset){object.traverse(o=>{if(o.isMesh){o.castShadow=asset.category!=='flower';o.receiveShadow=true;}});}root.add(object);meshes.set(record.id,object);return object;}
  function renderAll(){for(const object of meshes.values())disposeObject(object);meshes.clear();for(const record of state.objects)objectFor(record);select(selectedId);app.renderer.shadowMap.needsUpdate=true;}
  function snapshot(next,label){past.push(deep(state));if(past.length>80)past.shift();future.length=0;state=next;state.revision=(state.revision||0)+1;write(state);renderAll();ui.status.textContent=label;}
  function pointIn(asset,x,z){return asset.placement.allowedZones.some(name=>{const b=surface.zones[name];return b&&x>=b.x[0]&&x<=b.x[1]&&z>=b.z[0]&&z<=b.z[1];});}
  function segmentDistance(x,z,a,b){const dx=b[0]-a[0],dz=b[1]-a[1],l=dx*dx+dz*dz,t=l?Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/l)):0;return Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz);}
  function validate(asset,x,z,scale,ignoreId){
   const p=asset.placement,r=asset.bounds.footprintRadius*scale,errors=[];if(surface.surfaceType(x,z)!==p.allowedSurface)errors.push('只能放在陆地');if(surface.distanceToShore(x,z)<p.shoreClearance)errors.push('离湖岸太近');if(!pointIn(asset,x,z))errors.push('不在开放建设区');
   const centre=surface.terrainHeight(x,z),corners=[[r,0],[-r,0],[0,r],[0,-r]].map(([dx,dz])=>surface.terrainHeight(x+dx,z+dz));if(corners.some(y=>!Number.isFinite(y)||Math.abs(y-centre)>p.maxSlope))errors.push('地形坡度过大');
   for(const q of surface.placements){if(!['house','tree','fence','path-stone'].includes(q.kind))continue;if(Math.hypot(x-q.x,z-q.z)<r+Math.min(q.radius||.3,4)+p.clearance){errors.push('与现有 '+q.kind+' 太近');break;}}
   for(const route of [...surface.paths,...surface.reserves,...surface.animalPaths]){const width=(route.radius||.35)+p.clearance+r;if(route.points?.some((b,i)=>i&&segmentDistance(x,z,route.points[i-1],b)<width)){errors.push('会阻挡道路或动物路线');break;}}
   for(const record of state.objects){if(record.id===ignoreId)continue;const other=catalog.get(record.assetId);if(!other)continue;const rr=other.bounds.footprintRadius*(record.scale||1);if(Math.hypot(x-record.position[0],z-record.position[2])<r+rr+p.clearance){errors.push('与已建对象太近');break;}}
   const count=state.objects.filter(o=>o.assetId===asset.id&&o.id!==ignoreId).length;if(count>=asset.budget.maxInstances)errors.push('该资产已达到数量上限');return {valid:!errors.length,errors,y:centre};
  }
  function rayPoint(event){const rect=app.renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,app.camera);const hit=terrain&&raycaster.intersectObject(terrain,false)[0];return hit?.point||null;}
  function makeGhost(id){if(ghost)disposeObject(ghost);ghost=catalog.create(id);ghost.name='build-preview';app.scene.add(ghost);preview=null;}
  function updatePreview(event){if(!active||!['place','move'].includes(tool))return;const id=tool==='move'?state.objects.find(o=>o.id===selectedId)?.assetId:assetId,asset=catalog.get(id);if(!asset)return;const point=rayPoint(event);if(!point)return;const snap=asset.placement.snap,x=Math.round(point.x/snap)*snap,z=Math.round(point.z/snap)*snap,record=state.objects.find(o=>o.id===selectedId),scale=record?.scale||1,ry=tool==='move'?(record?.rotationY||0):rotation,result=validate(asset,x,z,scale,tool==='move'?selectedId:null);if(!ghost||ghost.userData.assetId!==id)makeGhost(id);ghost.position.set(x,result.y,z);ghost.rotation.y=ry;ghost.scale.setScalar(scale);materialGhost(ghost,result.valid);preview={x,z,y:result.y,valid:result.valid,errors:result.errors,asset,scale,rotationY:ry};ui.status.textContent=result.valid?'可以放置':result.errors.join('；');}
  function clearGhost(){if(ghost){disposeObject(ghost);ghost=null;}preview=null;}
  function select(id){selectedId=state.objects.some(o=>o.id===id)?id:null;if(selection){app.scene.remove(selection);selection.geometry?.dispose();selection.material?.dispose();selection=null;}if(selectedId&&meshes.get(selectedId)){selection=new T.BoxHelper(meshes.get(selectedId),0xffd45c);selection.material.depthTest=false;selection.renderOrder=200;app.scene.add(selection);ui.status.textContent='已选择对象';}}
  function setTool(next,id){tool=next;assetId=id||assetId;clearGhost();if(next==='place'&&assetId){rotation=0;makeGhost(assetId);}ui.panel.dataset.tool=tool;}
  function pick(event){const rect=app.renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,app.camera);const hit=raycaster.intersectObjects([...meshes.values()],true)[0];let object=hit?.object;while(object&&!object.userData.worldObjectId)object=object.parent;select(object?.userData.worldObjectId||null);}
  function commitPreview(){if(!preview?.valid)return;if(tool==='place'){const next=deep(state);next.objects.push({id:uid(),assetId:preview.asset.id,assetVersion:preview.asset.version,position:[preview.x,preview.y,preview.z],rotationY:preview.rotationY,scale:preview.scale,state:{growthStage:'complete'},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),revision:1});snapshot(next,'已放置 '+preview.asset.displayName);}else if(tool==='move'&&selectedId){const next=deep(state),record=next.objects.find(o=>o.id===selectedId);record.position=[preview.x,preview.y,preview.z];record.updatedAt=new Date().toISOString();record.revision++;snapshot(next,'对象已移动');setTool('select');}}
  function command(name){
   if(name==='close')return setActive(false);if(name==='select')return setTool('select');if(name==='move'){if(selectedId)setTool('move');else ui.status.textContent='请先选择一个对象';return;}
   if(name==='rotate'){const record=state.objects.find(o=>o.id===selectedId),asset=record&&catalog.get(record.assetId);if(!record||!asset){ui.status.textContent='请先选择一个对象';return;}const next=deep(state),target=next.objects.find(o=>o.id===selectedId),angle=target.rotationY+asset.placement.rotationStep,result=validate(asset,target.position[0],target.position[2],target.scale||1,target.id);if(!result.valid){ui.status.textContent=result.errors.join('；');return;}target.rotationY=angle;target.updatedAt=new Date().toISOString();target.revision++;snapshot(next,'对象已旋转');return;}
   if(name==='delete'){if(!selectedId){ui.status.textContent='请先选择一个对象';return;}const next=deep(state);next.objects=next.objects.filter(o=>o.id!==selectedId);selectedId=null;snapshot(next,'对象已移除');return;}
   if(name==='undo'&&past.length){future.push(deep(state));state=past.pop();write(state);renderAll();ui.status.textContent='已撤销';return;}if(name==='redo'&&future.length){past.push(deep(state));state=future.pop();write(state);renderAll();ui.status.textContent='已重做';return;}
  }
  function setActive(value){active=!!value;ui.panel.hidden=!active;ui.toggle.setAttribute('aria-expanded',String(active));ui.toggle.classList.toggle('active',active);if(!active){setTool('select');select(null);ui.status.textContent='已退出建造模式';}else ui.status.textContent='请选择资产或已有对象';}
  ui.toggle.addEventListener('click',()=>setActive(!active));ui.panel.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.asset){setTool('place',button.dataset.asset);ui.status.textContent='点击地面放置 '+catalog.get(button.dataset.asset).displayName;}else if(button.dataset.command)command(button.dataset.command);});
  app.renderer.domElement.addEventListener('pointermove',updatePreview,true);app.renderer.domElement.addEventListener('click',event=>{if(!active)return;event.preventDefault();event.stopImmediatePropagation();if(tool==='select')pick(event);else commitPreview();},true);addEventListener('keydown',event=>{if(!active)return;if(event.key==='Escape')setActive(false);if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();command(event.shiftKey?'redo':'undo');}});
  renderAll();return {catalog,root,get state(){return deep(state);},setActive,validate,dispose(){clearGhost();select(null);for(const object of meshes.values())disposeObject(object);root.removeFromParent();ui.toggle.remove();ui.panel.remove();}};
 }
 return {init,STORAGE,SAVE_VERSION};
})();
