/* Original procedural bark, pine needles and distant tree silhouettes. No reference photo is redistributed. */
window.LandscapeAssets=(()=>{
 function random(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
 function texture(w,h,draw){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.encoding=THREE.sRGBEncoding;return t;}
 function needles(){return texture(256,128,(c,w,h)=>{const rand=random(12);c.strokeStyle='#b1bba0';c.lineWidth=2;c.beginPath();c.moveTo(8,64);c.lineTo(248,64);c.stroke();for(let i=0;i<280;i++){let x=8+rand()*235,y=64+(rand()-.5)*10;c.strokeStyle=['#61775b','#9eab85','#cad1a6','#788d67'][i%4];c.lineWidth=.8+rand();c.beginPath();c.moveTo(x,y);c.lineTo(x+12+rand()*22,y+(i%2?1:-1)*(8+rand()*35)*Math.sin(x/w*Math.PI));c.stroke();}});}
 function pine(){return texture(256,512,(c,w,h)=>{const rand=random(43);c.strokeStyle='#867d66';c.lineWidth=4;c.beginPath();c.moveTo(128,510);c.lineTo(128,12);c.stroke();for(let j=0;j<42;j++){const y=22+j*10,width=(y/512)*110*(.6+rand()*.4);for(let side of [-1,1]){c.strokeStyle='#698069';c.lineWidth=2;c.beginPath();c.moveTo(128,y);c.lineTo(128+side*width,y+22);c.stroke();for(let k=0;k<40;k++){const f=rand(),x=128+side*width*f,yy=y+22*f;c.strokeStyle=['#526951','#809776','#384f44'][k%3];c.lineWidth=1.5;c.beginPath();c.moveTo(x,yy);c.lineTo(x+side*(3+rand()*13),yy+7+rand()*10);c.stroke();}}}});}
 function bark(){return texture(128,256,(c,w,h)=>{const rand=random(7);c.fillStyle='#726b5e';c.fillRect(0,0,w,h);for(let i=0;i<480;i++){c.strokeStyle=i%3?'#514d45':'#969082';c.lineWidth=.4+rand()*2;c.beginPath();let x=rand()*w,y=rand()*h;c.moveTo(x,y);c.lineTo(x+rand()*4,y+4+rand()*35);c.stroke();}});}
 function merge(parts){const positions=[],normals=[],uv=[];parts.forEach(([g,m])=>{const geo=g.index?g.toNonIndexed():g.clone();geo.applyMatrix4(m);positions.push(...geo.attributes.position.array);normals.push(...geo.attributes.normal.array);uv.push(...geo.attributes.uv.array);geo.dispose();});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));return g;}
 function pineGeometry(){const parts=[],dummy=new THREE.Object3D(),plane=new THREE.PlaneGeometry(1,1);for(let j=0;j<11;j++){const y=.23+j*.065,radius=(1-y)*.38;for(let k=0;k<5;k++){const a=k*Math.PI*2/5+j*2.4;dummy.position.set(Math.cos(a)*radius*.55,y,Math.sin(a)*radius*.55);dummy.rotation.set(-.25,k*1.7+j,.3);dummy.scale.set(radius*2.3,.11+.1*(1-y),1);dummy.updateMatrix();parts.push([plane,dummy.matrix.clone()]);dummy.rotation.y+=Math.PI/2;dummy.updateMatrix();parts.push([plane,dummy.matrix.clone()]);}}const out=merge(parts);plane.dispose();return out;}
 return {random,texture,needles,pine,bark,merge,pineGeometry};
})();
