/* Standalone visual studies. No imports from room.js, environment.js or other projects. */
window.ArchDemo=(()=>{const T=THREE;
 function create(theme){const scene=new T.Scene(),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;document.body.prepend(renderer.domElement);scene.background=new T.Color(theme==='school'?'#e9ede8':'#ede8df');const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,250),controls=new T.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=8;controls.maxDistance=180;scene.add(new T.HemisphereLight('#dae8ef','#8c795f',.7));const sun=new T.DirectionalLight('#fff0d8',1.7);sun.position.set(-25,35,24);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-34,right:34,top:34,bottom:-34,near:1,far:110});sun.shadow.normalBias=.025;scene.add(sun);
 const groups={},batches=new Map(),materials=new Map(),unit=new T.BoxGeometry(1,1,1),dummy=new T.Object3D(),features=[],spawn=[];let view='exterior';
 const group=n=>groups[n]||(groups[n]=(()=>{const g=new T.Group();g.name=n;scene.add(g);return g;})());
 function mat(color,roughness=.85){const k=color+roughness;if(!materials.has(k))materials.set(k,new T.MeshStandardMaterial({color:new T.Color(color).convertSRGBToLinear(),roughness}));return materials.get(k);}
 function box(color,x,y,z,w,h,d,section='structure',ry=0){const m=typeof color==='string'?mat(color):color,k=section+'/'+m.uuid;if(!batches.has(k))batches.set(k,{section,m,transforms:[]});dummy.position.set(x,y,z);dummy.rotation.set(0,ry,0);dummy.scale.set(w,h,d);dummy.updateMatrix();batches.get(k).transforms.push(dummy.matrix.clone());}
 function mesh(g,m,x,y,z,section='structure'){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;group(section).add(o);return o;}
 function text(words,x,y,z,w,h,color='#f4f1e6',bg='#28514b',section='signs'){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,1024,256);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 65px sans-serif';ctx.fillText(words,512,128,940);const map=new T.CanvasTexture(c);map.encoding=T.sRGBEncoding;const o=mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map}),x,y,z,section);o.castShadow=false;return o;}
 function tree(x,z,s=1){box('#776552',x,1.2*s,z,.22*s,2.4*s,.22*s,'landscape');for(let i=0;i<3;i++){const o=mesh(new T.IcosahedronGeometry(1,1),mat(['#7d956c','#62856a','#9daa78'][i]),x+(i-1)*.45*s,2.5*s+i*.35*s,z+i*.3*s,'landscape');o.scale.set(1.1*s,1.35*s,s);}}
 function marker(id,x,z,color){spawn.push({id,position:[x,.1,z],yaw:Math.PI});const ring=mesh(new T.RingGeometry(.55,.68,36),new T.MeshBasicMaterial({color,side:T.DoubleSide}),x,.04,z,'markers');ring.rotation.x=-Math.PI/2;const sign=text(id.includes('entry')?'ENTRY':'RETURN',x,.75,z,1.6,.4,'#ffffff',color,'markers');sign.userData.spawn=id;}
 function feature(id,description){features.push({id,description});}
 function finish(views,onView){for(const b of batches.values()){const o=new T.InstancedMesh(unit,b.m,b.transforms.length);b.transforms.forEach((m,i)=>o.setMatrixAt(i,m));o.castShadow=!b.m.transparent;o.receiveShadow=true;group(b.section).add(o);}function setView(id){view=id;onView?.(id,groups);const q=views[id];camera.position.fromArray(q.position);controls.target.fromArray(q.target);if(innerWidth<700)camera.position.sub(controls.target).multiplyScalar(2).add(controls.target);camera.lookAt(controls.target);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('markers').onclick=()=>{group('markers').visible=!group('markers').visible;};setView('exterior');let stopped=false;const tick=()=>{if(stopped)return;requestAnimationFrame(tick);controls.update();renderer.render(scene,camera);};tick();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.__DEMO__={scene,camera,renderer,controls,features,spawn,views,setView,get view(){return view;},dispose(){stopped=true;controls.dispose();renderer.dispose();}};return __DEMO__;}
 return {scene,camera,renderer,controls,sun,group,mat,box,mesh,text,tree,marker,feature,finish};}
 return {create};})();
